# Generated by Django 4.1.1 on 2022-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epigrafe', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to=None)),
                ('piefoto', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=None)),
                ('clasificacion', models.CharField(choices=[('Ciencias', 'Ciencia'), ('Negocio', 'Negocio'), ('Política', 'Política'), ('Salud', 'Salud'), ('Cultura', 'Cultura'), ('Tecnología', 'Tecnología')], max_length=20)),
            ],
        ),
    ]
