# Generated by Django 4.1.1 on 2022-10-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0002_alter_noticia_clasificacion_alter_noticia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='file',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clasificacion',
            field=models.CharField(choices=[('Ciencias', 'Ciencia'), ('Tecnología', 'Tecnología'), ('Negocio', 'Negocio'), ('Cultura', 'Cultura'), ('Salud', 'Salud'), ('Política', 'Política')], max_length=20),
        ),
    ]
