# Generated by Django 4.1.1 on 2022-10-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0004_remove_noticia_imagen_alter_noticia_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clasificacion',
            field=models.CharField(choices=[('Negocio', 'Negocio'), ('Ciencias', 'Ciencia'), ('Política', 'Política'), ('Tecnología', 'Tecnología'), ('Cultura', 'Cultura'), ('Salud', 'Salud')], max_length=20),
        ),
    ]
