# Generated by Django 4.1.1 on 2022-10-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0005_noticia_imagen_alter_noticia_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='noticia',
            name='clasificacion',
            field=models.ManyToManyField(to='sistnews.clasificacion'),
        ),
    ]
