# Generated by Django 4.1.1 on 2022-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0006_clasificacion_remove_noticia_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
