# Generated by Django 4.1.1 on 2022-10-10 03:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0007_clasificacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=tinymce.models.HTMLField(),
        ),
    ]
