# Generated by Django 4.1.1 on 2022-10-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0008_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='clasificacion',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='epigrafe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistnews.clasificacion'),
        ),
    ]
