# Generated by Django 4.1.1 on 2022-10-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistnews', '0009_remove_noticia_clasificacion_alter_noticia_epigrafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='clasificacion',
            field=models.CharField(choices=[('General', 'General'), ('Tecnologia', 'Tecnologia'), ('Cultura', 'Cultura'), ('Ciencia', 'Ciencia'), ('Negocio', 'Negocio'), ('Salud', 'Salud')], max_length=20),
        ),
    ]
