# Generated by Django 4.1.1 on 2022-10-12 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistnews', '0010_alter_noticia_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='createdBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clasificacion',
            field=models.CharField(choices=[('General', 'General'), ('Tecnologia', 'Tecnologia'), ('Cultura', 'Cultura'), ('Ciencia', 'Ciencia'), ('Negocio', 'Negocio'), ('Salud', 'Salud')], max_length=20, null=True),
        ),
    ]
