# Generated by Django 4.1.1 on 2022-10-12 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistnews', '0011_noticia_createdby_alter_noticia_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='clasificacion',
            field=models.CharField(choices=[('General', 'General'), ('Tecnologia', 'Tecnologia'), ('Cultura', 'Cultura'), ('Ciencia', 'Ciencia'), ('Negocio', 'Negocio'), ('Salud', 'Salud')], max_length=20, null=True, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='createdBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=tinymce.models.HTMLField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='epigrafe',
            field=models.CharField(max_length=200, null=True, verbose_name='Epígrafe'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='piefoto',
            field=models.CharField(max_length=100, verbose_name='Pie de Foto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
